Repository JECT-Study/JECT-1-FE, pull requests merged in 2025-07, with the labels that each got.

#5 Feat/mypage
  app.config.js
  app/(tabs)/_layout.tsx
  app/(tabs)/my.tsx
  app/(tabs)/my/edit_profile.tsx
  app/(tabs)/my/index.tsx
  app/(tabs)/my/like.tsx
  app/(tabs)/my/terms.tsx
  app/_layout.tsx
  app/my/terms/service_terms.tsx
  app/my/withdrawal.tsx
  components/icons/CalendarEditIcon.tsx
  components/icons/CameraIcon.tsx
  components/icons/Chevron.tsx
  components/icons/DiaryIcon.tsx
  components/icons/Edit.tsx
  components/icons/HeartIcon.tsx
  components/icons/X.tsx
  components/mypage/EditProfileHeader.tsx
  components/mypage/EditProfileImage.tsx
  components/mypage/EditProfileNickname.tsx
  components/mypage/LikeFilter.tsx
  components/mypage/MyMenus.tsx
  components/mypage/MyPageMenu.tsx
  components/mypage/MyPageMenus.tsx
  components/mypage/UserInfo.tsx
  components/mypage/WithDrawForm.tsx
  components/ui/CustomHeader.tsx
  constants/Colors.ts
  constants/Routes.ts
  constants/TabScreens.ts
  constants/WithDrawal.ts
  features/user/imagePicker.ts
  hooks/usePageNavigation.ts
  hooks/useWithDrawForm.ts
  package-lock.json
  package.json
  scripts/reset-project.js
  stores/useEditProfileStore.ts
  stores/useModalStateStore.ts
Labels: ✨feature, 👩🏻‍💻frontend, 😓help wanted

#6 일정 별 컨텐츠 화면 프론트 개발
  app/(tabs)/schedule.tsx
  components/icons/Chevron.tsx
  components/icons/ChevronIndicator.tsx
  components/icons/DropdownIcon.tsx
  components/schedule/ScheduleEmptyState.tsx
  components/schedule/ScheduleItem.tsx
  constants/CalendarTheme.ts
  constants/ScheduleData.ts
  package-lock.json
  package.json
Labels: ✔︎pull requests, ✨feature

#8 Update/survey
  app.config.js
  app/survey/index.tsx
  assets/images/survey/balloon.png
  components/alert/SurveyAlert.tsx
  components/icons/Chevron.tsx
  components/survey/Confetti.tsx
  components/survey/Percentage.tsx
  components/survey/SurveyBalloon.tsx
  components/survey/SurveyIntro.tsx
  components/survey/SurveyStep.tsx
  components/survey/SurveyStepBar.tsx
  components/ui/CustomHeader.tsx
  constants/Surveys.ts
  eas.json
  features/survey/chunkOption.ts
  package-lock.json
  package.json
  tailwind.config.js
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻frontend

#10 Feat/searchpage
  app.config.js
  app/(tabs)/my/like.tsx
  app/(tabs)/my/plan.tsx
  app/(tabs)/search.tsx
  app/(tabs)/search_tab.tsx
  app/_layout.tsx
  app/index.tsx
  app/search/index.tsx
  components/icons/X.tsx
  components/login/AppleLogin.tsx
  components/login/KakaoLogin.tsx
  components/login/SocialLoginButtons.tsx
  components/mypage/MyMenus.tsx
  components/search/RecentSearch.tsx
  components/search/RecentSearchListButton.tsx
  components/search/RecentSearchStatus.tsx
  components/search/SearchFilter.tsx
  components/search/SearchResult.tsx
  constants/ApiUrls.ts
  constants/Categories.ts
  constants/Regions.ts
  constants/Routes.ts
  constants/TabScreens.ts
  hooks/usePageNavigation.ts
  hooks/useRecentSearch.ts
  interfaces/search.interfaces.ts
  package-lock.json
  package.json
Labels: ✨feature, 👩🏻‍💻frontend

#11 Fix/naver map web, vercel 배포 github action
  .github/workflows/deploy.yml
  app.config.js
  app/(tabs)/detail/[id].tsx
  components/map/NaverMap.native.tsx
  components/map/NaverMap.tsx
  components/map/NaverMap.web.tsx
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻frontend, 😓help wanted
